// File: kamus-data.js
// Berisi daftar kosakata lengkap Indonesia - Inggris beserta pelafalan dan tipe katanya.
// Data sudah diurutkan berdasarkan 'indonesia' untuk Binary Search.

const dataKamus = [
    { indonesia: 'abu-abu', inggris: 'gray', pelafalan: 'grei', tipe: 'kata sifat' },
    { indonesia: 'air', inggris: 'water', pelafalan: 'wo-ter', tipe: 'kata benda' },
    { indonesia: 'akhir', inggris: 'end / final', pelafalan: 'end / fai-nel', tipe: 'kata benda / kata sifat' },
    { indonesia: 'aku', inggris: 'i / me', pelafalan: 'ai / mi', tipe: 'pronomina' },
    { indonesia: 'alas', inggris: 'reason / base', pelafalan: 'ri-zen / beis', tipe: 'kata benda' },
    { indonesia: 'alat', inggris: 'tool / device', pelafalan: 'tuul / di-vais', tipe: 'kata benda' },
    { indonesia: 'aman', inggris: 'safe / secure', pelafalan: 'seif / si-kyur', tipe: 'kata sifat' },
    { indonesia: 'ambil', inggris: 'take', pelafalan: 'teik', tipe: 'kata kerja' },
    { indonesia: 'anak', inggris: 'child', pelafalan: 'chaild', tipe: 'kata benda' },
    { indonesia: 'anda', inggris: 'you', pelafalan: 'yu', tipe: 'pronomina' },
    { indonesia: 'aneh', inggris: 'weird / strange', pelafalan: 'wi-erd / streinj', tipe: 'kata sifat' },
    { indonesia: 'angka', inggris: 'number / digit', pelafalan: 'nam-ber / di-jit', tipe: 'kata benda' },
    { indonesia: 'angin', inggris: 'wind', pelafalan: 'wind', tipe: 'kata benda' },
    { indonesia: 'anjing', inggris: 'dog', pelafalan: 'dog', tipe: 'kata benda' },
    { indonesia: 'api', inggris: 'fire', pelafalan: 'fai-er', tipe: 'kata benda' },
    { indonesia: 'apel', inggris: 'apple', pelafalan: 'e-pel', tipe: 'kata benda' },
    { indonesia: 'atas', inggris: 'up / above', pelafalan: 'ap / e-bav', tipe: 'kata keterangan / preposisi' },
    { indonesia: 'atau', inggris: 'or', pelafalan: 'or', tipe: 'konjungsi' },
    { indonesia: 'awal', inggris: 'beginning / initial', pelafalan: 'bi-gi-ning / i-ni-syel', tipe: 'kata benda / kata sifat' },
    { indonesia: 'awan', inggris: 'cloud', pelafalan: 'klaud', tipe: 'kata benda' },
    { indonesia: 'ayah', inggris: 'father', pelafalan: 'fa-dher', tipe: 'kata benda' },
    { indonesia: 'ayam', inggris: 'chicken', pelafalan: 'ci-ken', tipe: 'kata benda' },
    { indonesia: 'baca', inggris: 'read', pelafalan: 'riid', tipe: 'kata kerja' },
    { indonesia: 'bahagia', inggris: 'happy', pelafalan: 'he-pi', tipe: 'kata sifat' },
    { indonesia: 'bahasa', inggris: 'language', pelafalan: 'leng-gwij', tipe: 'kata benda' },
    { indonesia: 'bahaya', inggris: 'danger', pelafalan: 'deyn-jer', tipe: 'kata benda' },
    { indonesia: 'bahkan', inggris: 'even', pelafalan: 'i-ven', tipe: 'kata keterangan' },
    { indonesia: 'baik', inggris: 'good / well', pelafalan: 'gud / wel', tipe: 'kata sifat / kata keterangan' },
    { indonesia: 'baju', inggris: 'shirt / clothes', pelafalan: 'shert / klodz', tipe: 'kata benda' },
    { indonesia: 'bangun', inggris: 'wake up / build', pelafalan: 'weik ap / bild', tipe: 'kata kerja' },
    { indonesia: 'banyak', inggris: 'many / much', pelafalan: 'me-ni / mac', tipe: 'kata sifat / kata keterangan' },
    { indonesia: 'bantal', inggris: 'pillow', pelafalan: 'pi-lo', tipe: 'kata benda' },
    { indonesia: 'bantu', inggris: 'help', pelafalan: 'help', tipe: 'kata kerja' },
    { indonesia: 'baru', inggris: 'new', pelafalan: 'nyu', tipe: 'kata sifat' },
    { indonesia: 'bawah', inggris: 'down / below', pelafalan: 'daun / bi-lo', tipe: 'kata keterangan / preposisi' },
    { indonesia: 'bayar', inggris: 'pay', pelafalan: 'pei', tipe: 'kata kerja' },
    { indonesia: 'bayi', inggris: 'baby', pelafalan: 'bei-bi', tipe: 'kata benda' },
    { indonesia: 'bebek', inggris: 'duck', pelafalan: 'dak', tipe: 'kata benda' },
    { indonesia: 'bekerja', inggris: 'to work', pelafalan: 'tu werk', tipe: 'kata kerja' },
    { indonesia: 'belajar', inggris: 'learn / study', pelafalan: 'lern / sta-di', tipe: 'kata kerja' },
    { indonesia: 'belakang', inggris: 'back / behind', pelafalan: 'bek / bi-haind', tipe: 'kata benda / kata keterangan' },
    { indonesia: 'beli', inggris: 'buy', pelafalan: 'bai', tipe: 'kata kerja' },
    { indonesia: 'benar', inggris: 'correct / true', pelafalan: 'ko-rekt / truu', tipe: 'kata sifat' },
    { indonesia: 'benci', inggris: 'hate', pelafalan: 'heit', tipe: 'kata kerja' },
    { indonesia: 'beras', inggris: 'uncooked rice', pelafalan: 'an-kukd rais', tipe: 'kata benda' },
    { indonesia: 'berat', inggris: 'heavy', pelafalan: 'he-vi', tipe: 'kata sifat' },
    { indonesia: 'berbicara', inggris: 'speak / talk', pelafalan: 'spiik / tok', tipe: 'kata kerja' },
    { indonesia: 'berenang', inggris: 'swim', pelafalan: 'swim', tipe: 'kata kerja' },
    { indonesia: 'berhenti', inggris: 'stop', pelafalan: 'stop', tipe: 'kata kerja' },
    { indonesia: 'bermain', inggris: 'play', pelafalan: 'plei', tipe: 'kata kerja' },
    { indonesia: 'bersih', inggris: 'clean', pelafalan: 'kliin', tipe: 'kata sifat / kata kerja' },
    { indonesia: 'bertanya', inggris: 'ask', pelafalan: 'aask', tipe: 'kata kerja' },
    { indonesia: 'besar', inggris: 'big / large', pelafalan: 'big / larj', tipe: 'kata sifat' },
    { indonesia: 'besi', inggris: 'iron', pelafalan: 'ai-ern', tipe: 'kata benda' },
    { indonesia: 'besok', inggris: 'tomorrow', pelafalan: 'tu-mo-ro', tipe: 'kata keterangan' },
    { indonesia: 'hijau', inggris: 'green', pelafalan: 'griin', tipe: 'kata sifat' },
    { indonesia: 'hilang', inggris: 'lost / disappear', pelafalan: 'lost / dis-e-pir', tipe: 'kata sifat / kata kerja' },
    { indonesia: 'hitam', inggris: 'black', pelafalan: 'blek', tipe: 'kata sifat' },
    { indonesia: 'hujan', inggris: 'rain', pelafalan: 'rein', tipe: 'kata benda / kata kerja' },
    { indonesia: 'hutan', inggris: 'forest', pelafalan: 'fo-rest', tipe: 'kata benda' },
    { indonesia: 'ibu', inggris: 'mother', pelafalan: 'ma-dher', tipe: 'kata benda' },
    { indonesia: 'ikan', inggris: 'fish', pelafalan: 'fish', tipe: 'kata benda / kata kerja' },
    { indonesia: 'ikut', inggris: 'follow / join', pelafalan: 'fo-lo / join', tipe: 'kata kerja' },
    { indonesia: 'ingat', inggris: 'remember', pelafalan: 'ri-mem-ber', tipe: 'kata kerja' },
    { indonesia: 'ingin', inggris: 'want', pelafalan: 'want', tipe: 'kata kerja' },
    { indonesia: 'ini', inggris: 'this', pelafalan: 'dhis', tipe: 'pronomina / penentu' },
    { indonesia: 'istri', inggris: 'wife', pelafalan: 'waif', tipe: 'kata benda' },
    { indonesia: 'itu', inggris: 'that', pelafalan: 'dhet', tipe: 'pronomina / penentu' },
    { indonesia: 'jadi', inggris: 'so / become', pelafalan: 'so / bi-kam', tipe: 'konjungsi / kata kerja' },
    { indonesia: 'jalan', inggris: 'street / walk', pelafalan: 'striit / wok', tipe: 'kata benda / kata kerja' },
    { indonesia: 'jam', inggris: 'hour / clock', pelafalan: 'au-er / klok', tipe: 'kata benda' },
    { indonesia: 'janji', inggris: 'promise', pelafalan: 'pro-mis', tipe: 'kata benda / kata kerja' },
    { indonesia: 'jantung', inggris: 'heart (organ)', pelafalan: 'hart', tipe: 'kata benda' },
    { indonesia: 'jari', inggris: 'finger', pelafalan: 'fing-ger', tipe: 'kata benda' },
    { indonesia: 'jatuh', inggris: 'fall', pelafalan: 'fol', tipe: 'kata kerja' },
    { indonesia: 'jauh', inggris: 'far', pelafalan: 'far', tipe: 'kata sifat / kata keterangan' },
    { indonesia: 'jawab', inggris: 'answer', pelafalan: 'an-ser', tipe: 'kata benda / kata kerja' },
    { indonesia: 'jendela', inggris: 'window', pelafalan: 'win-do', tipe: 'kata benda' },
    { indonesia: 'jual', inggris: 'sell', pelafalan: 'sel', tipe: 'kata kerja' },
    { indonesia: 'juga', inggris: 'also / too', pelafalan: 'ol-so / tuu', tipe: 'kata keterangan' },
    { indonesia: 'kaca', inggris: 'glass / mirror', pelafalan: 'glas / mir-ror', tipe: 'kata benda' },
    { indonesia: 'kain', inggris: 'fabric / cloth', pelafalan: 'fa-brik / kloth', tipe: 'kata benda' },
    { indonesia: 'kakak', inggris: 'older sibling', pelafalan: 'ol-der si-bling', tipe: 'kata benda' },
    { indonesia: 'kaki', inggris: 'foot / leg', pelafalan: 'fut / leg', tipe: 'kata benda' },
    { indonesia: 'kalah', inggris: 'lose', pelafalan: 'luuz', tipe: 'kata kerja' }, // bisa juga 'defeated' (ks)
    { indonesia: 'kamar', inggris: 'room', pelafalan: 'ruum', tipe: 'kata benda' },
    { indonesia: 'kamera', inggris: 'camera', pelafalan: 'ka-me-ra', tipe: 'kata benda' },
    { indonesia: 'kami', inggris: 'we / us (exclusive)', pelafalan: 'wi / as', tipe: 'pronomina' },
    { indonesia: 'kamu', inggris: 'you', pelafalan: 'yu', tipe: 'pronomina' },
    { indonesia: 'kanan', inggris: 'right', pelafalan: 'rait', tipe: 'kata sifat / kata benda' },
    { indonesia: 'kantor', inggris: 'office', pelafalan: 'o-fis', tipe: 'kata benda' },
    { indonesia: 'kapan', inggris: 'when', pelafalan: 'wen', tipe: 'kata tanya / kata keterangan' },
    { indonesia: 'karena', inggris: 'because', pelafalan: 'bi-koz', tipe: 'konjungsi' },
    { indonesia: 'kasih', inggris: 'give / love', pelafalan: 'giv / lav', tipe: 'kata kerja / kata benda' },
    { indonesia: 'kasur', inggris: 'mattress', pelafalan: 'ma-tres', tipe: 'kata benda' },
    { indonesia: 'kata', inggris: 'word', pelafalan: 'werd', tipe: 'kata benda' },
    { indonesia: 'kayu', inggris: 'wood', pelafalan: 'wud', tipe: 'kata benda' },
    { indonesia: 'kecil', inggris: 'small', pelafalan: 'smol', tipe: 'kata sifat' },
    { indonesia: 'keluarga', inggris: 'family', pelafalan: 'fa-mi-li', tipe: 'kata benda' },
    { indonesia: 'kenapa', inggris: 'why', pelafalan: 'wai', tipe: 'kata tanya / kata keterangan' },
    { indonesia: 'kepala', inggris: 'head', pelafalan: 'hed', tipe: 'kata benda' },
    { indonesia: 'kertas', inggris: 'paper', pelafalan: 'pei-per', tipe: 'kata benda' },
    { indonesia: 'kiri', inggris: 'left', pelafalan: 'left', tipe: 'kata sifat / kata benda' },
    { indonesia: 'kirim', inggris: 'send', pelafalan: 'send', tipe: 'kata kerja' },
    { indonesia: 'kita', inggris: 'we (inclusive)', pelafalan: 'wi', tipe: 'pronomina' },
    { indonesia: 'kotor', inggris: 'dirty', pelafalan: 'der-ti', tipe: 'kata sifat' },
    { indonesia: 'kucing', inggris: 'cat', pelafalan: 'ket', tipe: 'kata benda' },
    { indonesia: 'kuda', inggris: 'horse', pelafalan: 'hors', tipe: 'kata benda' },
    { indonesia: 'kulit', inggris: 'skin', pelafalan: 'skin', tipe: 'kata benda' },
    { indonesia: 'kunci', inggris: 'key', pelafalan: 'kii', tipe: 'kata benda / kata kerja' },
    { indonesia: 'kuning', inggris: 'yellow', pelafalan: 'ye-lo', tipe: 'kata sifat' },
    { indonesia: 'kursi', inggris: 'chair', pelafalan: 'cher', tipe: 'kata benda' },
    { indonesia: 'lagu', inggris: 'song', pelafalan: 'song', tipe: 'kata benda' },
    { indonesia: 'laki-laki', inggris: 'male / man', pelafalan: 'meil / men', tipe: 'kata sifat / kata benda' },
    { indonesia: 'lama', inggris: 'long (time) / old', pelafalan: 'long / old', tipe: 'kata sifat' },
    { indonesia: 'lampu', inggris: 'lamp', pelafalan: 'lemp', tipe: 'kata benda' },
    { indonesia: 'langit', inggris: 'sky', pelafalan: 'skai', tipe: 'kata benda' },
    { indonesia: 'lapar', inggris: 'hungry', pelafalan: 'hang-gri', tipe: 'kata sifat' },
    { indonesia: 'lari', inggris: 'run', pelafalan: 'ran', tipe: 'kata kerja / kata benda' },
    { indonesia: 'laut', inggris: 'sea', pelafalan: 'sii', tipe: 'kata benda' },
    { indonesia: 'lebih', inggris: 'more', pelafalan: 'mor', tipe: 'kata keterangan' },
    { indonesia: 'lemari', inggris: 'cupboard / closet', pelafalan: 'kap-berd / klo-zet', tipe: 'kata benda' },
    { indonesia: 'lewat', inggris: 'pass', pelafalan: 'pas', tipe: 'kata kerja / preposisi' },
    { indonesia: 'lihat', inggris: 'see', pelafalan: 'sii', tipe: 'kata kerja' },
    { indonesia: 'lima', inggris: 'five', pelafalan: 'faiv', tipe: 'numeralia' },
    { indonesia: 'luar', inggris: 'outside', pelafalan: 'aut-said', tipe: 'kata keterangan / preposisi' },
    { indonesia: 'lupa', inggris: 'forget', pelafalan: 'for-get', tipe: 'kata kerja' },
    { indonesia: 'maaf', inggris: 'sorry', pelafalan: 'so-ri', tipe: 'kata seru / kata sifat' },
    { indonesia: 'mahal', inggris: 'expensive', pelafalan: 'iks-pen-siv', tipe: 'kata sifat' },
    { indonesia: 'main', inggris: 'play', pelafalan: 'plei', tipe: 'kata kerja / kata benda' },
    { indonesia: 'makan', inggris: 'eat', pelafalan: 'iit', tipe: 'kata kerja' },
    { indonesia: 'malam', inggris: 'night', pelafalan: 'nait', tipe: 'kata benda' },
    { indonesia: 'malas', inggris: 'lazy', pelafalan: 'lei-zi', tipe: 'kata sifat' },
    { indonesia: 'mana', inggris: 'where', pelafalan: 'wer', tipe: 'kata tanya / kata keterangan' },
    { indonesia: 'manis', inggris: 'sweet', pelafalan: 'swiit', tipe: 'kata sifat' },
    { indonesia: 'masak', inggris: 'cook', pelafalan: 'kuk', tipe: 'kata kerja' },
    { indonesia: 'masalah', inggris: 'problem', pelafalan: 'pro-blem', tipe: 'kata benda' },
    { indonesia: 'masuk', inggris: 'enter', pelafalan: 'en-ter', tipe: 'kata kerja' },
    { indonesia: 'mata', inggris: 'eye', pelafalan: 'ai', tipe: 'kata benda' },
    { indonesia: 'matahari', inggris: 'sun', pelafalan: 'san', tipe: 'kata benda' },
    { indonesia: 'mati', inggris: 'die / dead', pelafalan: 'dai / ded', tipe: 'kata kerja / kata sifat' },
    { indonesia: 'meja', inggris: 'table', pelafalan: 'tei-bel', tipe: 'kata benda' },
    { indonesia: 'menang', inggris: 'win', pelafalan: 'win', tipe: 'kata kerja' },
    { indonesia: 'menangis', inggris: 'cry', pelafalan: 'krai', tipe: 'kata kerja' },
    { indonesia: 'mengerti', inggris: 'understand', pelafalan: 'an-der-stend', tipe: 'kata kerja' },
    { indonesia: 'menunggu', inggris: 'wait', pelafalan: 'weit', tipe: 'kata kerja' },
    { indonesia: 'menulis', inggris: 'write', pelafalan: 'rait', tipe: 'kata kerja' },
    { indonesia: 'merah', inggris: 'red', pelafalan: 'red', tipe: 'kata sifat' },
    { indonesia: 'mereka', inggris: 'they / them', pelafalan: 'dhei / dhem', tipe: 'pronomina' },
    { indonesia: 'minum', inggris: 'drink', pelafalan: 'drink', tipe: 'kata kerja / kata benda' },
    { indonesia: 'mobil', inggris: 'car', pelafalan: 'kar', tipe: 'kata benda' },
    { indonesia: 'muda', inggris: 'young', pelafalan: 'yang', tipe: 'kata sifat' },
    { indonesia: 'mudah', inggris: 'easy', pelafalan: 'i-zi', tipe: 'kata sifat' },
    { indonesia: 'mulai', inggris: 'start', pelafalan: 'start', tipe: 'kata kerja' },
    { indonesia: 'mulut', inggris: 'mouth', pelafalan: 'mauth', tipe: 'kata benda' },
    { indonesia: 'murah', inggris: 'cheap', pelafalan: 'ciip', tipe: 'kata sifat' },
    { indonesia: 'musik', inggris: 'music', pelafalan: 'myu-zik', tipe: 'kata benda' },
    { indonesia: 'naik', inggris: 'go up / ride', pelafalan: 'go ap / raid', tipe: 'kata kerja' },
    { indonesia: 'nama', inggris: 'name', pelafalan: 'neim', tipe: 'kata benda' },
    { indonesia: 'nasi', inggris: 'cooked rice', pelafalan: 'kukd rais', tipe: 'kata benda' },
    { indonesia: 'nomor', inggris: 'number', pelafalan: 'nam-ber', tipe: 'kata benda' },
    { indonesia: 'nyata', inggris: 'real', pelafalan: 'ri-el', tipe: 'kata sifat' },
    { indonesia: 'obat', inggris: 'medicine', pelafalan: 'me-di-sin', tipe: 'kata benda' },
    { indonesia: 'orang', inggris: 'person / people', pelafalan: 'per-sen / pii-pel', tipe: 'kata benda' },
    { indonesia: 'pagi', inggris: 'morning', pelafalan: 'mor-ning', tipe: 'kata benda' },
    { indonesia: 'pakaian', inggris: 'clothing', pelafalan: 'klo-dhing', tipe: 'kata benda' },
    { indonesia: 'panas', inggris: 'hot', pelafalan: 'hot', tipe: 'kata sifat' },
    { indonesia: 'panjang', inggris: 'long (length)', pelafalan: 'long', tipe: 'kata sifat' },
    { indonesia: 'papan', inggris: 'board', pelafalan: 'bord', tipe: 'kata benda' },
    { indonesia: 'pasar', inggris: 'market', pelafalan: 'mar-ket', tipe: 'kata benda' },
    { indonesia: 'pelan', inggris: 'slow', pelafalan: 'slo', tipe: 'kata sifat / kata keterangan' },
    { indonesia: 'pena', inggris: 'pen', pelafalan: 'pen', tipe: 'kata benda' },
    { indonesia: 'pendek', inggris: 'short', pelafalan: 'short', tipe: 'kata sifat' },
    { indonesia: 'pensil', inggris: 'pencil', pelafalan: 'pen-sil', tipe: 'kata benda' },
    { indonesia: 'percaya', inggris: 'believe / trust', pelafalan: 'bi-liiv / trast', tipe: 'kata kerja' },
    { indonesia: 'perempuan', inggris: 'female / woman', pelafalan: 'fi-meil / wu-men', tipe: 'kata sifat / kata benda' },
    { indonesia: 'pergi', inggris: 'go', pelafalan: 'go', tipe: 'kata kerja' },
    { indonesia: 'perlu', inggris: 'need', pelafalan: 'niid', tipe: 'kata kerja' },
    { indonesia: 'perut', inggris: 'stomach', pelafalan: 'sta-mak', tipe: 'kata benda' },
    { indonesia: 'pintu', inggris: 'door', pelafalan: 'dor', tipe: 'kata benda' },
    { indonesia: 'pintar', inggris: 'smart', pelafalan: 'smart', tipe: 'kata sifat' },
    { indonesia: 'pohon', inggris: 'tree', pelafalan: 'trii', tipe: 'kata benda' },
    { indonesia: 'polisi', inggris: 'police', pelafalan: 'po-liis', tipe: 'kata benda' },
    { indonesia: 'pulang', inggris: 'go home', pelafalan: 'go hom', tipe: 'kata kerja' },
    { indonesia: 'pulau', inggris: 'island', pelafalan: 'ai-lend', tipe: 'kata benda' },
    { indonesia: 'putih', inggris: 'white', pelafalan: 'wait', tipe: 'kata sifat' },
    { indonesia: 'rambut', inggris: 'hair', pelafalan: 'her', tipe: 'kata benda' },
    { indonesia: 'rasa', inggris: 'taste / feel', pelafalan: 'teist / fiil', tipe: 'kata benda / kata kerja' },
    { indonesia: 'roti', inggris: 'bread', pelafalan: 'bred', tipe: 'kata benda' },
    { indonesia: 'ruang', inggris: 'space / room', pelafalan: 'speis / ruum', tipe: 'kata benda' },
    { indonesia: 'rumah', inggris: 'house', pelafalan: 'haus', tipe: 'kata benda' },
    { indonesia: 'rusak', inggris: 'broken / damaged', pelafalan: 'bro-ken / de-mejd', tipe: 'kata sifat' },
    { indonesia: 'sabun', inggris: 'soap', pelafalan: 'sop', tipe: 'kata benda' },
    { indonesia: 'sakit', inggris: 'sick / pain', pelafalan: 'sik / pein', tipe: 'kata sifat / kata benda' },
    { indonesia: 'salah', inggris: 'wrong', pelafalan: 'rong', tipe: 'kata sifat' },
    { indonesia: 'sama', inggris: 'same', pelafalan: 'seim', tipe: 'kata sifat / preposisi' },
    { indonesia: 'sampah', inggris: 'trash / rubbish', pelafalan: 'trash / ra-bish', tipe: 'kata benda' },
    { indonesia: 'sangat', inggris: 'very', pelafalan: 've-ri', tipe: 'kata keterangan' },
    { indonesia: 'sapi', inggris: 'cow', pelafalan: 'kau', tipe: 'kata benda' },
    { indonesia: 'satu', inggris: 'one', pelafalan: 'wan', tipe: 'numeralia' },
    { indonesia: 'sayur', inggris: 'vegetable', pelafalan: 've-je-te-bel', tipe: 'kata benda' },
    { indonesia: 'sebentar', inggris: 'a moment', pelafalan: 'e mo-ment', tipe: 'kata keterangan' },
    { indonesia: 'sebelum', inggris: 'before', pelafalan: 'bi-for', tipe: 'preposisi / konjungsi' },
    { indonesia: 'sekarang', inggris: 'now', pelafalan: 'nau', tipe: 'kata keterangan' },
    { indonesia: 'sekolah', inggris: 'school', pelafalan: 'skuul', tipe: 'kata benda' },
    { indonesia: 'selalu', inggris: 'always', pelafalan: 'ol-weiz', tipe: 'kata keterangan' },
    { indonesia: 'selamat', inggris: 'safe / congratulations', pelafalan: 'seif / kon-gra-tu-lei-syens', tipe: 'kata sifat / kata seru' },
    { indonesia: 'selatan', inggris: 'south', pelafalan: 'sauth', tipe: 'kata benda / kata sifat' },
    { indonesia: 'selesai', inggris: 'finished', pelafalan: 'fi-nishd', tipe: 'kata sifat / kata kerja' },
    { indonesia: 'semua', inggris: 'all', pelafalan: 'ol', tipe: 'penentu / pronomina' },
    { indonesia: 'sendiri', inggris: 'self / alone', pelafalan: 'self / e-lon', tipe: 'pronomina / kata keterangan' },
    { indonesia: 'sepatu', inggris: 'shoes', pelafalan: 'syuuz', tipe: 'kata benda' },
    { indonesia: 'seperti', inggris: 'like / as', pelafalan: 'laik / ez', tipe: 'preposisi / konjungsi' },
    { indonesia: 'sesudah', inggris: 'after', pelafalan: 'af-ter', tipe: 'preposisi / konjungsi' },
    { indonesia: 'siang', inggris: 'afternoon', pelafalan: 'af-ter-nuun', tipe: 'kata benda' },
    { indonesia: 'siapa', inggris: 'who', pelafalan: 'huu', tipe: 'kata tanya / pronomina' },
    { indonesia: 'sini', inggris: 'here', pelafalan: 'hir', tipe: 'kata keterangan' },
    { indonesia: 'sore', inggris: 'late afternoon / evening', pelafalan: 'leit af-ter-nuun / iiv-ning', tipe: 'kata benda' },
    { indonesia: 'suami', inggris: 'husband', pelafalan: 'has-bend', tipe: 'kata benda' },
    { indonesia: 'suara', inggris: 'voice / sound', pelafalan: 'vois / saund', tipe: 'kata benda' },
    { indonesia: 'sudah', inggris: 'already', pelafalan: 'ol-re-di', tipe: 'kata keterangan' },
    { indonesia: 'suka', inggris: 'like', pelafalan: 'laik', tipe: 'kata kerja' },
    { indonesia: 'sungai', inggris: 'river', pelafalan: 'ri-ver', tipe: 'kata benda' },
    { indonesia: 'surat', inggris: 'letter', pelafalan: 'le-ter', tipe: 'kata benda' },
    { indonesia: 'susah', inggris: 'difficult', pelafalan: 'di-fi-kelt', tipe: 'kata sifat' },
    { indonesia: 'susu', inggris: 'milk', pelafalan: 'milk', tipe: 'kata benda' },
    { indonesia: 'tahu', inggris: 'know / tofu', pelafalan: 'no / to-fu', tipe: 'kata kerja / kata benda' },
    { indonesia: 'tahun', inggris: 'year', pelafalan: 'yir', tipe: 'kata benda' },
    { indonesia: 'takut', inggris: 'afraid', pelafalan: 'e-freid', tipe: 'kata sifat' },
    { indonesia: 'taman', inggris: 'park / garden', pelafalan: 'park / gar-den', tipe: 'kata benda' },
    { indonesia: 'tanah', inggris: 'soil / land', pelafalan: 'soil / lend', tipe: 'kata benda' },
    { indonesia: 'tangan', inggris: 'hand', pelafalan: 'hend', tipe: 'kata benda' },
    { indonesia: 'tanggal', inggris: 'date', pelafalan: 'deit', tipe: 'kata benda' },
    { indonesia: 'tanya', inggris: 'ask', pelafalan: 'aask', tipe: 'kata kerja' },
    { indonesia: 'tapi', inggris: 'but', pelafalan: 'bat', tipe: 'konjungsi' },
    { indonesia: 'tas', inggris: 'bag', pelafalan: 'beg', tipe: 'kata benda' },
    { indonesia: 'teh', inggris: 'tea', pelafalan: 'tii', tipe: 'kata benda' },
    { indonesia: 'teman', inggris: 'friend', pelafalan: 'frend', tipe: 'kata benda' },
    { indonesia: 'tempat', inggris: 'place', pelafalan: 'pleis', tipe: 'kata benda' },
    { indonesia: 'tengah', inggris: 'middle / center', pelafalan: 'mi-del / sen-ter', tipe: 'kata benda / kata sifat' },
    { indonesia: 'tentang', inggris: 'about', pelafalan: 'e-baut', tipe: 'preposisi' },
    { indonesia: 'terakhir', inggris: 'last', pelafalan: 'last', tipe: 'kata sifat / kata keterangan' },
    { indonesia: 'terbang', inggris: 'fly', pelafalan: 'flai', tipe: 'kata kerja' },
    { indonesia: 'terima kasih', inggris: 'thank you', pelafalan: 'theng kyu', tipe: 'ungkapan' },
    { indonesia: 'tertawa', inggris: 'laugh', pelafalan: 'laf', tipe: 'kata kerja' },
    { indonesia: 'tetapi', inggris: 'but / however', pelafalan: 'bat / hau-e-ver', tipe: 'konjungsi' },
    { indonesia: 'tidur', inggris: 'sleep', pelafalan: 'sliip', tipe: 'kata kerja / kata benda' },
    { indonesia: 'timur', inggris: 'east', pelafalan: 'iist', tipe: 'kata benda / kata sifat' },
    { indonesia: 'tinggi', inggris: 'tall / high', pelafalan: 'tol / hai', tipe: 'kata sifat' },
    { indonesia: 'toko', inggris: 'shop / store', pelafalan: 'shop / stor', tipe: 'kata benda' },
    { indonesia: 'topi', inggris: 'hat', pelafalan: 'het', tipe: 'kata benda' },
    { indonesia: 'tua', inggris: 'old', pelafalan: 'old', tipe: 'kata sifat' },
    { indonesia: 'tulang', inggris: 'bone', pelafalan: 'bon', tipe: 'kata benda' },
    { indonesia: 'tulis', inggris: 'write', pelafalan: 'rait', tipe: 'kata kerja' },
    { indonesia: 'tunggu', inggris: 'wait', pelafalan: 'weit', tipe: 'kata kerja' },
    { indonesia: 'uang', inggris: 'money', pelafalan: 'ma-ni', tipe: 'kata benda' },
    { indonesia: 'udara', inggris: 'air', pelafalan: 'er', tipe: 'kata benda' },
    { indonesia: 'utara', inggris: 'north', pelafalan: 'north', tipe: 'kata benda / kata sifat' },
    { indonesia: 'wajah', inggris: 'face', pelafalan: 'feis', tipe: 'kata benda' },
    { indonesia: 'waktu', inggris: 'time', pelafalan: 'taim', tipe: 'kata benda' },
    { indonesia: 'wanita', inggris: 'woman', pelafalan: 'wu-men', tipe: 'kata benda' },
    { indonesia: 'warna', inggris: 'color', pelafalan: 'ka-ler', tipe: 'kata benda' },
    { indonesia: 'ya', inggris: 'yes', pelafalan: 'yes', tipe: 'kata seru' },
    { indonesia: 'yang', inggris: 'which / that', pelafalan: 'wich / dhet', tipe: 'kata ganti penghubung' }
];