// File: kamus-data.js
// Berisi daftar kosakata lengkap Indonesia - Inggris beserta pelafalannya.
// Data sudah diurutkan berdasarkan 'indonesia' untuk Binary Search.

const dataKamus = [
    { indonesia: 'abu-abu', inggris: 'gray', pelafalan: 'grei' },
    { indonesia: 'air', inggris: 'water', pelafalan: 'wo-ter' },
    { indonesia: 'akhir', inggris: 'end / final', pelafalan: 'end / fai-nel' },
    { indonesia: 'aku', inggris: 'i / me', pelafalan: 'ai / mi' },
    { indonesia: 'alas', inggris: 'reason / base', pelafalan: 'ri-zen / beis' },
    { indonesia: 'alat', inggris: 'tool / device', pelafalan: 'tuul / di-vais' },
    { indonesia: 'aman', inggris: 'safe / secure', pelafalan: 'seif / si-kyur' },
    { indonesia: 'ambil', inggris: 'take', pelafalan: 'teik' },
    { indonesia: 'anak', inggris: 'child', pelafalan: 'chaild' },
    { indonesia: 'anda', inggris: 'you', pelafalan: 'yu' },
    { indonesia: 'aneh', inggris: 'weird / strange', pelafalan: 'wi-erd / streinj' },
    { indonesia: 'angka', inggris: 'number / digit', pelafalan: 'nam-ber / di-jit' },
    { indonesia: 'angin', inggris: 'wind', pelafalan: 'wind' },
    { indonesia: 'anjing', inggris: 'dog', pelafalan: 'dog' },
    { indonesia: 'api', inggris: 'fire', pelafalan: 'fai-er' },
    { indonesia: 'apel', inggris: 'apple', pelafalan: 'e-pel' },
    { indonesia: 'atas', inggris: 'up / above', pelafalan: 'ap / e-bav' },
    { indonesia: 'atau', inggris: 'or', pelafalan: 'or' },
    { indonesia: 'awal', inggris: 'beginning / initial', pelafalan: 'bi-gi-ning / i-ni-syel' },
    { indonesia: 'awan', inggris: 'cloud', pelafalan: 'klaud' },
    { indonesia: 'ayah', inggris: 'father', pelafalan: 'fa-dher' },
    { indonesia: 'ayam', inggris: 'chicken', pelafalan: 'ci-ken' },
    { indonesia: 'baca', inggris: 'read', pelafalan: 'riid' },
    { indonesia: 'bahagia', inggris: 'happy', pelafalan: 'he-pi' },
    { indonesia: 'bahasa', inggris: 'language', pelafalan: 'leng-gwij' },
    { indonesia: 'bahaya', inggris: 'danger', pelafalan: 'deyn-jer' },
    { indonesia: 'bahkan', inggris: 'even', pelafalan: 'i-ven' },
    { indonesia: 'baik', inggris: 'good / well', pelafalan: 'gud / wel' },
    { indonesia: 'baju', inggris: 'shirt / clothes', pelafalan: 'shert / klodz' },
    { indonesia: 'bangun', inggris: 'wake up / build', pelafalan: 'weik ap / bild' },
    { indonesia: 'banyak', inggris: 'many / much', pelafalan: 'me-ni / mac' },
    { indonesia: 'bantal', inggris: 'pillow', pelafalan: 'pi-lo' },
    { indonesia: 'bantu', inggris: 'help', pelafalan: 'help' },
    { indonesia: 'baru', inggris: 'new', pelafalan: 'nyu' },
    { indonesia: 'bawah', inggris: 'down / below', pelafalan: 'daun / bi-lo' },
    { indonesia: 'bayar', inggris: 'pay', pelafalan: 'pei' },
    { indonesia: 'bayi', inggris: 'baby', pelafalan: 'bei-bi' },
    { indonesia: 'bebek', inggris: 'duck', pelafalan: 'dak' },
    { indonesia: 'bekerja', inggris: 'to work', pelafalan: 'tu werk' },
    { indonesia: 'belajar', inggris: 'learn / study', pelafalan: 'lern / sta-di' },
    { indonesia: 'belakang', inggris: 'back / behind', pelafalan: 'bek / bi-haind' },
    { indonesia: 'beli', inggris: 'buy', pelafalan: 'bai' },
    { indonesia: 'benar', inggris: 'correct / true', pelafalan: 'ko-rekt / truu' },
    { indonesia: 'benci', inggris: 'hate', pelafalan: 'heit' },
    { indonesia: 'beras', inggris: 'uncooked rice', pelafalan: 'an-kukd rais' },
    { indonesia: 'berat', inggris: 'heavy', pelafalan: 'he-vi' },
    { indonesia: 'berbicara', inggris: 'speak / talk', pelafalan: 'spiik / tok' },
    { indonesia: 'berenang', inggris: 'swim', pelafalan: 'swim' },
    { indonesia: 'berhenti', inggris: 'stop', pelafalan: 'stop' },
    { indonesia: 'bermain', inggris: 'play', pelafalan: 'plei' },
    { indonesia: 'bersih', inggris: 'clean', pelafalan: 'kliin' },
    { indonesia: 'bertanya', inggris: 'ask', pelafalan: 'aask' },
    { indonesia: 'besar', inggris: 'big / large', pelafalan: 'big / larj' },
    { indonesia: 'besi', inggris: 'iron', pelafalan: 'ai-ern' },
    { indonesia: 'besok', inggris: 'tomorrow', pelafalan: 'tu-mo-ro' },
    { indonesia: 'hijau', inggris: 'green', pelafalan: 'griin' },
    { indonesia: 'hilang', inggris: 'lost / disappear', pelafalan: 'lost / dis-e-pir' },
    { indonesia: 'hitam', inggris: 'black', pelafalan: 'blek' },
    { indonesia: 'hujan', inggris: 'rain', pelafalan: 'rein' },
    { indonesia: 'hutan', inggris: 'forest', pelafalan: 'fo-rest' },
    { indonesia: 'ibu', inggris: 'mother', pelafalan: 'ma-dher' },
    { indonesia: 'ikan', inggris: 'fish', pelafalan: 'fish' },
    { indonesia: 'ikut', inggris: 'follow / join', pelafalan: 'fo-lo / join' },
    { indonesia: 'ingat', inggris: 'remember', pelafalan: 'ri-mem-ber' },
    { indonesia: 'ingin', inggris: 'want', pelafalan: 'want' },
    { indonesia: 'ini', inggris: 'this', pelafalan: 'dhis' },
    { indonesia: 'istri', inggris: 'wife', pelafalan: 'waif' },
    { indonesia: 'itu', inggris: 'that', pelafalan: 'dhet' },
    { indonesia: 'jadi', inggris: 'so / become', pelafalan: 'so / bi-kam' },
    { indonesia: 'jalan', inggris: 'street / walk', pelafalan: 'striit / wok' },
    { indonesia: 'jam', inggris: 'hour / clock', pelafalan: 'au-er / klok' },
    { indonesia: 'janji', inggris: 'promise', pelafalan: 'pro-mis' },
    { indonesia: 'jantung', inggris: 'heart (organ)', pelafalan: 'hart' },
    { indonesia: 'jari', inggris: 'finger', pelafalan: 'fing-ger' },
    { indonesia: 'jatuh', inggris: 'fall', pelafalan: 'fol' },
    { indonesia: 'jauh', inggris: 'far', pelafalan: 'far' },
    { indonesia: 'jawab', inggris: 'answer', pelafalan: 'an-ser' },
    { indonesia: 'jendela', inggris: 'window', pelafalan: 'win-do' },
    { indonesia: 'jual', inggris: 'sell', pelafalan: 'sel' },
    { indonesia: 'juga', inggris: 'also / too', pelafalan: 'ol-so / tuu' },
    { indonesia: 'kaca', inggris: 'glass / mirror', pelafalan: 'glas / mir-ror' },
    { indonesia: 'kain', inggris: 'fabric / cloth', pelafalan: 'fa-brik / kloth' },
    { indonesia: 'kakak', inggris: 'older sibling', pelafalan: 'ol-der si-bling' },
    { indonesia: 'kaki', inggris: 'foot / leg', pelafalan: 'fut / leg' },
    { indonesia: 'kalah', inggris: 'lose', pelafalan: 'luuz' },
    { indonesia: 'kamar', inggris: 'room', pelafalan: 'ruum' },
    { indonesia: 'kamera', inggris: 'camera', pelafalan: 'ka-me-ra' },
    { indonesia: 'kami', inggris: 'we / us (exclusive)', pelafalan: 'wi / as' },
    { indonesia: 'kamu', inggris: 'you', pelafalan: 'yu' },
    { indonesia: 'kanan', inggris: 'right', pelafalan: 'rait' },
    { indonesia: 'kantor', inggris: 'office', pelafalan: 'o-fis' },
    { indonesia: 'kapan', inggris: 'when', pelafalan: 'wen' },
    { indonesia: 'karena', inggris: 'because', pelafalan: 'bi-koz' },
    { indonesia: 'kasih', inggris: 'give / love', pelafalan: 'giv / lav' },
    { indonesia: 'kasur', inggris: 'mattress', pelafalan: 'ma-tres' },
    { indonesia: 'kata', inggris: 'word', pelafalan: 'werd' },
    { indonesia: 'kayu', inggris: 'wood', pelafalan: 'wud' },
    { indonesia: 'kecil', inggris: 'small', pelafalan: 'smol' },
    { indonesia: 'keluarga', inggris: 'family', pelafalan: 'fa-mi-li' },
    { indonesia: 'kenapa', inggris: 'why', pelafalan: 'wai' },
    { indonesia: 'kepala', inggris: 'head', pelafalan: 'hed' },
    { indonesia: 'kertas', inggris: 'paper', pelafalan: 'pei-per' },
    { indonesia: 'kiri', inggris: 'left', pelafalan: 'left' },
    { indonesia: 'kirim', inggris: 'send', pelafalan: 'send' },
    { indonesia: 'kita', inggris: 'we (inclusive)', pelafalan: 'wi' },
    { indonesia: 'kotor', inggris: 'dirty', pelafalan: 'der-ti' },
    { indonesia: 'kucing', inggris: 'cat', pelafalan: 'ket' },
    { indonesia: 'kuda', inggris: 'horse', pelafalan: 'hors' },
    { indonesia: 'kulit', inggris: 'skin', pelafalan: 'skin' },
    { indonesia: 'kunci', inggris: 'key', pelafalan: 'kii' },
    { indonesia: 'kuning', inggris: 'yellow', pelafalan: 'ye-lo' },
    { indonesia: 'kursi', inggris: 'chair', pelafalan: 'cher' },
    { indonesia: 'lagu', inggris: 'song', pelafalan: 'song' },
    { indonesia: 'laki-laki', inggris: 'male / man', pelafalan: 'meil / men' },
    { indonesia: 'lama', inggris: 'long (time) / old', pelafalan: 'long / old' },
    { indonesia: 'lampu', inggris: 'lamp', pelafalan: 'lemp' },
    { indonesia: 'langit', inggris: 'sky', pelafalan: 'skai' },
    { indonesia: 'lapar', inggris: 'hungry', pelafalan: 'hang-gri' },
    { indonesia: 'lari', inggris: 'run', pelafalan: 'ran' },
    { indonesia: 'laut', inggris: 'sea', pelafalan: 'sii' },
    { indonesia: 'lebih', inggris: 'more', pelafalan: 'mor' },
    { indonesia: 'lemari', inggris: 'cupboard / closet', pelafalan: 'kap-berd / klo-zet' },
    { indonesia: 'lewat', inggris: 'pass', pelafalan: 'pas' },
    { indonesia: 'lihat', inggris: 'see', pelafalan: 'sii' },
    { indonesia: 'lima', inggris: 'five', pelafalan: 'faiv' },
    { indonesia: 'luar', inggris: 'outside', pelafalan: 'aut-said' },
    { indonesia: 'lupa', inggris: 'forget', pelafalan: 'for-get' },
    { indonesia: 'maaf', inggris: 'sorry', pelafalan: 'so-ri' },
    { indonesia: 'mahal', inggris: 'expensive', pelafalan: 'iks-pen-siv' },
    { indonesia: 'main', inggris: 'play', pelafalan: 'plei' },
    { indonesia: 'makan', inggris: 'eat', pelafalan: 'iit' },
    { indonesia: 'malam', inggris: 'night', pelafalan: 'nait' },
    { indonesia: 'malas', inggris: 'lazy', pelafalan: 'lei-zi' },
    { indonesia: 'mana', inggris: 'where', pelafalan: 'wer' },
    { indonesia: 'manis', inggris: 'sweet', pelafalan: 'swiit' },
    { indonesia: 'masak', inggris: 'cook', pelafalan: 'kuk' },
    { indonesia: 'masalah', inggris: 'problem', pelafalan: 'pro-blem' },
    { indonesia: 'masuk', inggris: 'enter', pelafalan: 'en-ter' },
    { indonesia: 'mata', inggris: 'eye', pelafalan: 'ai' },
    { indonesia: 'matahari', inggris: 'sun', pelafalan: 'san' },
    { indonesia: 'mati', inggris: 'die / dead', pelafalan: 'dai / ded' },
    { indonesia: 'meja', inggris: 'table', pelafalan: 'tei-bel' },
    { indonesia: 'menang', inggris: 'win', pelafalan: 'win' },
    { indonesia: 'menangis', inggris: 'cry', pelafalan: 'krai' },
    { indonesia: 'mengerti', inggris: 'understand', pelafalan: 'an-der-stend' },
    { indonesia: 'menunggu', inggris: 'wait', pelafalan: 'weit' },
    { indonesia: 'menulis', inggris: 'write', pelafalan: 'rait' },
    { indonesia: 'merah', inggris: 'red', pelafalan: 'red' },
    { indonesia: 'mereka', inggris: 'they / them', pelafalan: 'dhei / dhem' },
    { indonesia: 'minum', inggris: 'drink', pelafalan: 'drink' },
    { indonesia: 'mobil', inggris: 'car', pelafalan: 'kar' },
    { indonesia: 'muda', inggris: 'young', pelafalan: 'yang' },
    { indonesia: 'mudah', inggris: 'easy', pelafalan: 'i-zi' },
    { indonesia: 'mulai', inggris: 'start', pelafalan: 'start' },
    { indonesia: 'mulut', inggris: 'mouth', pelafalan: 'mauth' },
    { indonesia: 'murah', inggris: 'cheap', pelafalan: 'ciip' },
    { indonesia: 'musik', inggris: 'music', pelafalan: 'myu-zik' },
    { indonesia: 'naik', inggris: 'go up / ride', pelafalan: 'go ap / raid' },
    { indonesia: 'nama', inggris: 'name', pelafalan: 'neim' },
    { indonesia: 'nasi', inggris: 'cooked rice', pelafalan: 'kukd rais' },
    { indonesia: 'nomor', inggris: 'number', pelafalan: 'nam-ber' },
    { indonesia: 'nyata', inggris: 'real', pelafalan: 'ri-el' },
    { indonesia: 'obat', inggris: 'medicine', pelafalan: 'me-di-sin' },
    { indonesia: 'orang', inggris: 'person / people', pelafalan: 'per-sen / pii-pel' },
    { indonesia: 'pagi', inggris: 'morning', pelafalan: 'mor-ning' },
    { indonesia: 'pakaian', inggris: 'clothing', pelafalan: 'klo-dhing' },
    { indonesia: 'panas', inggris: 'hot', pelafalan: 'hot' },
    { indonesia: 'panjang', inggris: 'long (length)', pelafalan: 'long' },
    { indonesia: 'papan', inggris: 'board', pelafalan: 'bord' },
    { indonesia: 'pasar', inggris: 'market', pelafalan: 'mar-ket' },
    { indonesia: 'pelan', inggris: 'slow', pelafalan: 'slo' },
    { indonesia: 'pena', inggris: 'pen', pelafalan: 'pen' },
    { indonesia: 'pendek', inggris: 'short', pelafalan: 'short' },
    { indonesia: 'pensil', inggris: 'pencil', pelafalan: 'pen-sil' },
    { indonesia: 'percaya', inggris: 'believe / trust', pelafalan: 'bi-liiv / trast' },
    { indonesia: 'perempuan', inggris: 'female / woman', pelafalan: 'fi-meil / wu-men' },
    { indonesia: 'pergi', inggris: 'go', pelafalan: 'go' },
    { indonesia: 'perlu', inggris: 'need', pelafalan: 'niid' },
    { indonesia: 'perut', inggris: 'stomach', pelafalan: 'sta-mak' },
    { indonesia: 'pintu', inggris: 'door', pelafalan: 'dor' },
    { indonesia: 'pintar', inggris: 'smart', pelafalan: 'smart' },
    { indonesia: 'pohon', inggris: 'tree', pelafalan: 'trii' },
    { indonesia: 'polisi', inggris: 'police', pelafalan: 'po-liis' },
    { indonesia: 'pulang', inggris: 'go home', pelafalan: 'go hom' },
    { indonesia: 'pulau', inggris: 'island', pelafalan: 'ai-lend' },
    { indonesia: 'putih', inggris: 'white', pelafalan: 'wait' },
    { indonesia: 'rambut', inggris: 'hair', pelafalan: 'her' },
    { indonesia: 'rasa', inggris: 'taste / feel', pelafalan: 'teist / fiil' },
    { indonesia: 'roti', inggris: 'bread', pelafalan: 'bred' },
    { indonesia: 'ruang', inggris: 'space / room', pelafalan: 'speis / ruum' },
    { indonesia: 'rumah', inggris: 'house', pelafalan: 'haus' },
    { indonesia: 'rusak', inggris: 'broken / damaged', pelafalan: 'bro-ken / de-mejd' },
    { indonesia: 'sabun', inggris: 'soap', pelafalan: 'sop' },
    { indonesia: 'sakit', inggris: 'sick / pain', pelafalan: 'sik / pein' },
    { indonesia: 'salah', inggris: 'wrong', pelafalan: 'rong' },
    { indonesia: 'sama', inggris: 'same', pelafalan: 'seim' },
    { indonesia: 'sampah', inggris: 'trash / rubbish', pelafalan: 'trash / ra-bish' },
    { indonesia: 'sangat', inggris: 'very', pelafalan: 've-ri' },
    { indonesia: 'sapi', inggris: 'cow', pelafalan: 'kau' },
    { indonesia: 'satu', inggris: 'one', pelafalan: 'wan' },
    { indonesia: 'sayur', inggris: 'vegetable', pelafalan: 've-je-te-bel' },
    { indonesia: 'sebentar', inggris: 'a moment', pelafalan: 'e mo-ment' },
    { indonesia: 'sebelum', inggris: 'before', pelafalan: 'bi-for' },
    { indonesia: 'sekarang', inggris: 'now', pelafalan: 'nau' },
    { indonesia: 'sekolah', inggris: 'school', pelafalan: 'skuul' },
    { indonesia: 'selalu', inggris: 'always', pelafalan: 'ol-weiz' },
    { indonesia: 'selamat', inggris: 'safe / congratulations', pelafalan: 'seif / kon-gra-tu-lei-syens' },
    { indonesia: 'selatan', inggris: 'south', pelafalan: 'sauth' },
    { indonesia: 'selesai', inggris: 'finished', pelafalan: 'fi-nishd' },
    { indonesia: 'semua', inggris: 'all', pelafalan: 'ol' },
    { indonesia: 'sendiri', inggris: 'self / alone', pelafalan: 'self / e-lon' },
    { indonesia: 'sepatu', inggris: 'shoes', pelafalan: 'syuuz' },
    { indonesia: 'seperti', inggris: 'like / as', pelafalan: 'laik / ez' },
    { indonesia: 'sesudah', inggris: 'after', pelafalan: 'af-ter' },
    { indonesia: 'siang', inggris: 'afternoon', pelafalan: 'af-ter-nuun' },
    { indonesia: 'siapa', inggris: 'who', pelafalan: 'huu' },
    { indonesia: 'sini', inggris: 'here', pelafalan: 'hir' },
    { indonesia: 'sore', inggris: 'late afternoon / evening', pelafalan: 'leit af-ter-nuun / iiv-ning' },
    { indonesia: 'suami', inggris: 'husband', pelafalan: 'has-bend' },
    { indonesia: 'suara', inggris: 'voice / sound', pelafalan: 'vois / saund' },
    { indonesia: 'sudah', inggris: 'already', pelafalan: 'ol-re-di' },
    { indonesia: 'suka', inggris: 'like', pelafalan: 'laik' },
    { indonesia: 'sungai', inggris: 'river', pelafalan: 'ri-ver' },
    { indonesia: 'surat', inggris: 'letter', pelafalan: 'le-ter' },
    { indonesia: 'susah', inggris: 'difficult', pelafalan: 'di-fi-kelt' },
    { indonesia: 'susu', inggris: 'milk', pelafalan: 'milk' },
    { indonesia: 'tahu', inggris: 'know / tofu', pelafalan: 'no / to-fu' },
    { indonesia: 'tahun', inggris: 'year', pelafalan: 'yir' },
    { indonesia: 'takut', inggris: 'afraid', pelafalan: 'e-freid' },
    { indonesia: 'taman', inggris: 'park / garden', pelafalan: 'park / gar-den' },
    { indonesia: 'tanah', inggris: 'soil / land', pelafalan: 'soil / lend' },
    { indonesia: 'tangan', inggris: 'hand', pelafalan: 'hend' },
    { indonesia: 'tanggal', inggris: 'date', pelafalan: 'deit' },
    { indonesia: 'tanya', inggris: 'ask', pelafalan: 'aask' },
    { indonesia: 'tapi', inggris: 'but', pelafalan: 'bat' },
    { indonesia: 'tas', inggris: 'bag', pelafalan: 'beg' },
    { indonesia: 'teh', inggris: 'tea', pelafalan: 'tii' },
    { indonesia: 'teman', inggris: 'friend', pelafalan: 'frend' },
    { indonesia: 'tempat', inggris: 'place', pelafalan: 'pleis' },
    { indonesia: 'tengah', inggris: 'middle / center', pelafalan: 'mi-del / sen-ter' },
    { indonesia: 'tentang', inggris: 'about', pelafalan: 'e-baut' },
    { indonesia: 'terakhir', inggris: 'last', pelafalan: 'last' },
    { indonesia: 'terbang', inggris: 'fly', pelafalan: 'flai' },
    { indonesia: 'terima kasih', inggris: 'thank you', pelafalan: 'theng kyu' },
    { indonesia: 'tertawa', inggris: 'laugh', pelafalan: 'laf' },
    { indonesia: 'tetapi', inggris: 'but / however', pelafalan: 'bat / hau-e-ver' },
    { indonesia: 'tidur', inggris: 'sleep', pelafalan: 'sliip' },
    { indonesia: 'timur', inggris: 'east', pelafalan: 'iist' },
    { indonesia: 'tinggi', inggris: 'tall / high', pelafalan: 'tol / hai' },
    { indonesia: 'toko', inggris: 'shop / store', pelafalan: 'shop / stor' },
    { indonesia: 'topi', inggris: 'hat', pelafalan: 'het' },
    { indonesia: 'tua', inggris: 'old', pelafalan: 'old' },
    { indonesia: 'tulang', inggris: 'bone', pelafalan: 'bon' },
    { indonesia: 'tulis', inggris: 'write', pelafalan: 'rait' },
    { indonesia: 'tunggu', inggris: 'wait', pelafalan: 'weit' },
    { indonesia: 'uang', inggris: 'money', pelafalan: 'ma-ni' },
    { indonesia: 'udara', inggris: 'air', pelafalan: 'er' },
    { indonesia: 'utara', inggris: 'north', pelafalan: 'north' },
    { indonesia: 'wajah', inggris: 'face', pelafalan: 'feis' },
    { indonesia: 'waktu', inggris: 'time', pelafalan: 'taim' },
    { indonesia: 'wanita', inggris: 'woman', pelafalan: 'wu-men' },
    { indonesia: 'warna', inggris: 'color', pelafalan: 'ka-ler' },
    { indonesia: 'ya', inggris: 'yes', pelafalan: 'yes' },
    { indonesia: 'yang', inggris: 'which / that', pelafalan: 'wich / dhet' }
];