// File: kamus-data.js
// Berisi daftar kosakata lengkap Indonesia - Inggris
// Data sudah diurutkan berdasarkan 'indonesia' untuk Binary Search.

const dataKamus = [
    { indonesia: 'abu-abu', inggris: 'gray' },
    { indonesia: 'air', inggris: 'water' },
    { indonesia: 'akhir', inggris: 'end / final' },
    { indonesia: 'aku', inggris: 'i / me' },
    { indonesia: 'alas', inggris: 'reason / base' },
    { indonesia: 'alat', inggris: 'tool / device' },
    { indonesia: 'aman', inggris: 'safe / secure' },
    { indonesia: 'ambil', inggris: 'take' },
    { indonesia: 'anak', inggris: 'child' },
    { indonesia: 'anda', inggris: 'you' },
    { indonesia: 'aneh', inggris: 'weird / strange' },
    { indonesia: 'angka', inggris: 'number / digit' },
    { indonesia: 'angin', inggris: 'wind' },
    { indonesia: 'anjing', inggris: 'dog' },
    { indonesia: 'api', inggris: 'fire' },
    { indonesia: 'apel', inggris: 'apple' },
    { indonesia: 'atas', inggris: 'up / above' },
    { indonesia: 'atau', inggris: 'or' },
    { indonesia: 'awal', inggris: 'beginning / initial' },
    { indonesia: 'awan', inggris: 'cloud' },
    { indonesia: 'ayah', inggris: 'father' },
    { indonesia: 'ayam', inggris: 'chicken' },
    { indonesia: 'baca', inggris: 'read' },
    { indonesia: 'bahagia', inggris: 'happy' },
    { indonesia: 'bahasa', inggris: 'language' },
    { indonesia: 'bahaya', inggris: 'danger' },
    { indonesia: 'bahkan', inggris: 'even' },
    { indonesia: 'baik', inggris: 'good / well' },
    { indonesia: 'baju', inggris: 'shirt / clothes' },
    { indonesia: 'bangun', inggris: 'wake up / build' },
    { indonesia: 'banyak', inggris: 'many / much' },
    { indonesia: 'bantal', inggris: 'pillow' },
    { indonesia: 'bantu', inggris: 'help' },
    { indonesia: 'baru', inggris: 'new' },
    { indonesia: 'bawah', inggris: 'down / below' },
    { indonesia: 'bayar', inggris: 'pay' },
    { indonesia: 'bayi', inggris: 'baby' },
    { indonesia: 'bebek', inggris: 'duck' },
    { indonesia: 'bekerja', inggris: 'to work' },
    { indonesia: 'belajar', inggris: 'learn / study' },
    { indonesia: 'belakang', inggris: 'back / behind' },
    { indonesia: 'beli', inggris: 'buy' },
    { indonesia: 'benar', inggris: 'correct / true' },
    { indonesia: 'benci', inggris: 'hate' },
    { indonesia: 'beras', inggris: 'uncooked rice' },
    { indonesia: 'berat', inggris: 'heavy' },
    { indonesia: 'berbicara', inggris: 'speak / talk' },
    { indonesia: 'berenang', inggris: 'swim' },
    { indonesia: 'berhenti', inggris: 'stop' },
    { indonesia: 'bermain', inggris: 'play' },
    { indonesia: 'bersih', inggris: 'clean' },
    { indonesia: 'bertanya', inggris: 'ask' },
    { indonesia: 'besar', inggris: 'big / large' },
    { indonesia: 'besi', inggris: 'iron' },
    { indonesia: 'besok', inggris: 'tomorrow' },
    { indonesia: 'hijau', inggris: 'green' },
    { indonesia: 'hilang', inggris: 'lost / disappear' },
    { indonesia: 'hitam', inggris: 'black' },
    { indonesia: 'hujan', inggris: 'rain' },
    { indonesia: 'hutan', inggris: 'forest' },
    { indonesia: 'ibu', inggris: 'mother' },
    { indonesia: 'ikan', inggris: 'fish' },
    { indonesia: 'ikut', inggris: 'follow / join' },
    { indonesia: 'ingat', inggris: 'remember' },
    { indonesia: 'ingin', inggris: 'want' },
    { indonesia: 'ini', inggris: 'this' },
    { indonesia: 'istri', inggris: 'wife' },
    { indonesia: 'itu', inggris: 'that' },
    { indonesia: 'jadi', inggris: 'so / become' },
    { indonesia: 'jalan', inggris: 'street / walk' },
    { indonesia: 'jam', inggris: 'hour / clock' },
    { indonesia: 'janji', inggris: 'promise' },
    { indonesia: 'jantung', inggris: 'heart (organ)' },
    { indonesia: 'jari', inggris: 'finger' },
    { indonesia: 'jatuh', inggris: 'fall' },
    { indonesia: 'jauh', inggris: 'far' },
    { indonesia: 'jawab', inggris: 'answer' },
    { indonesia: 'jendela', inggris: 'window' },
    { indonesia: 'jual', inggris: 'sell' },
    { indonesia: 'juga', inggris: 'also / too' },
    { indonesia: 'kaca', inggris: 'glass / mirror' },
    { indonesia: 'kain', inggris: 'fabric / cloth' },
    { indonesia: 'kakak', inggris: 'older sibling' },
    { indonesia: 'kaki', inggris: 'foot / leg' },
    { indonesia: 'kalah', inggris: 'lose' },
    { indonesia: 'kamar', inggris: 'room' },
    { indonesia: 'kamera', inggris: 'camera' },
    { indonesia: 'kami', inggris: 'we / us (exclusive)' },
    { indonesia: 'kamu', inggris: 'you' },
    { indonesia: 'kanan', inggris: 'right' },
    { indonesia: 'kantor', inggris: 'office' },
    { indonesia: 'kapan', inggris: 'when' },
    { indonesia: 'karena', inggris: 'because' },
    { indonesia: 'kasih', inggris: 'give / love' },
    { indonesia: 'kasur', inggris: 'mattress' },
    { indonesia: 'kata', inggris: 'word' },
    { indonesia: 'kayu', inggris: 'wood' },
    { indonesia: 'kecil', inggris: 'small' },
    { indonesia: 'keluarga', inggris: 'family' },
    { indonesia: 'kenapa', inggris: 'why' },
    { indonesia: 'kepala', inggris: 'head' },
    { indonesia: 'kertas', inggris: 'paper' },
    { indonesia: 'kiri', inggris: 'left' },
    { indonesia: 'kirim', inggris: 'send' },
    { indonesia: 'kita', inggris: 'we (inclusive)' },
    { indonesia: 'kotor', inggris: 'dirty' },
    { indonesia: 'kucing', inggris: 'cat' },
    { indonesia: 'kuda', inggris: 'horse' },
    { indonesia: 'kulit', inggris: 'skin' },
    { indonesia: 'kunci', inggris: 'key' },
    { indonesia: 'kuning', inggris: 'yellow' },
    { indonesia: 'kursi', inggris: 'chair' },
    { indonesia: 'lagu', inggris: 'song' },
    { indonesia: 'laki-laki', inggris: 'male / man' },
    { indonesia: 'lama', inggris: 'long (time) / old' },
    { indonesia: 'lampu', inggris: 'lamp' },
    { indonesia: 'langit', inggris: 'sky' },
    { indonesia: 'lapar', inggris: 'hungry' },
    { indonesia: 'lari', inggris: 'run' },
    { indonesia: 'laut', inggris: 'sea' },
    { indonesia: 'lebih', inggris: 'more' },
    { indonesia: 'lemari', inggris: 'cupboard / closet' },
    { indonesia: 'lewat', inggris: 'pass' },
    { indonesia: 'lihat', inggris: 'see' },
    { indonesia: 'lima', inggris: 'five' },
    { indonesia: 'luar', inggris: 'outside' },
    { indonesia: 'lupa', inggris: 'forget' },
    { indonesia: 'maaf', inggris: 'sorry' },
    { indonesia: 'mahal', inggris: 'expensive' },
    { indonesia: 'main', inggris: 'play' },
    { indonesia: 'makan', inggris: 'eat' },
    { indonesia: 'malam', inggris: 'night' },
    { indonesia: 'malas', inggris: 'lazy' },
    { indonesia: 'mana', inggris: 'where' },
    { indonesia: 'manis', inggris: 'sweet' },
    { indonesia: 'masak', inggris: 'cook' },
    { indonesia: 'masalah', inggris: 'problem' },
    { indonesia: 'masuk', inggris: 'enter' },
    { indonesia: 'mata', inggris: 'eye' },
    { indonesia: 'matahari', inggris: 'sun' },
    { indonesia: 'mati', inggris: 'die / dead' },
    { indonesia: 'meja', inggris: 'table' },
    { indonesia: 'menang', inggris: 'win' },
    { indonesia: 'menangis', inggris: 'cry' },
    { indonesia: 'mengerti', inggris: 'understand' },
    { indonesia: 'menunggu', inggris: 'wait' },
    { indonesia: 'menulis', inggris: 'write' },
    { indonesia: 'merah', inggris: 'red' },
    { indonesia: 'mereka', inggris: 'they / them' },
    { indonesia: 'minum', inggris: 'drink' },
    { indonesia: 'mobil', inggris: 'car' },
    { indonesia: 'muda', inggris: 'young' },
    { indonesia: 'mudah', inggris: 'easy' },
    { indonesia: 'mulai', inggris: 'start' },
    { indonesia: 'mulut', inggris: 'mouth' },
    { indonesia: 'murah', inggris: 'cheap' },
    { indonesia: 'musik', inggris: 'music' },
    { indonesia: 'naik', inggris: 'go up / ride' },
    { indonesia: 'nama', inggris: 'name' },
    { indonesia: 'nasi', inggris: 'cooked rice' },
    { indonesia: 'nomor', inggris: 'number' },
    { indonesia: 'nyata', inggris: 'real' },
    { indonesia: 'obat', inggris: 'medicine' },
    { indonesia: 'orang', inggris: 'person / people' },
    { indonesia: 'pagi', inggris: 'morning' },
    { indonesia: 'pakaian', inggris: 'clothing' },
    { indonesia: 'panas', inggris: 'hot' },
    { indonesia: 'panjang', inggris: 'long (length)' },
    { indonesia: 'papan', inggris: 'board' },
    { indonesia: 'pasar', inggris: 'market' },
    { indonesia: 'pelan', inggris: 'slow' },
    { indonesia: 'pena', inggris: 'pen' },
    { indonesia: 'pendek', inggris: 'short' },
    { indonesia: 'pensil', inggris: 'pencil' },
    { indonesia: 'percaya', inggris: 'believe / trust' },
    { indonesia: 'perempuan', inggris: 'female / woman' },
    { indonesia: 'pergi', inggris: 'go' },
    { indonesia: 'perlu', inggris: 'need' },
    { indonesia: 'perut', inggris: 'stomach' },
    { indonesia: 'pintu', inggris: 'door' },
    { indonesia: 'pintar', inggris: 'smart' },
    { indonesia: 'pohon', inggris: 'tree' },
    { indonesia: 'polisi', inggris: 'police' },
    { indonesia: 'pulang', inggris: 'go home' },
    { indonesia: 'pulau', inggris: 'island' },
    { indonesia: 'putih', inggris: 'white' },
    { indonesia: 'rambut', inggris: 'hair' },
    { indonesia: 'rasa', inggris: 'taste / feel' },
    { indonesia: 'roti', inggris: 'bread' },
    { indonesia: 'ruang', inggris: 'space / room' },
    { indonesia: 'rumah', inggris: 'house' },
    { indonesia: 'rusak', inggris: 'broken / damaged' },
    { indonesia: 'sabun', inggris: 'soap' },
    { indonesia: 'sakit', inggris: 'sick / pain' },
    { indonesia: 'salah', inggris: 'wrong' },
    { indonesia: 'sama', inggris: 'same' },
    { indonesia: 'sampah', inggris: 'trash / rubbish' },
    { indonesia: 'sangat', inggris: 'very' },
    { indonesia: 'sapi', inggris: 'cow' },
    { indonesia: 'satu', inggris: 'one' },
    { indonesia: 'sayur', inggris: 'vegetable' },
    { indonesia: 'sebentar', inggris: 'a moment' },
    { indonesia: 'sebelum', inggris: 'before' },
    { indonesia: 'sekarang', inggris: 'now' },
    { indonesia: 'sekolah', inggris: 'school' },
    { indonesia: 'selalu', inggris: 'always' },
    { indonesia: 'selamat', inggris: 'safe / congratulations' },
    { indonesia: 'selatan', inggris: 'south' },
    { indonesia: 'selesai', inggris: 'finished' },
    { indonesia: 'semua', inggris: 'all' },
    { indonesia: 'sendiri', inggris: 'self / alone' },
    { indonesia: 'sepatu', inggris: 'shoes' },
    { indonesia: 'seperti', inggris: 'like / as' },
    { indonesia: 'sesudah', inggris: 'after' },
    { indonesia: 'siang', inggris: 'afternoon' },
    { indonesia: 'siapa', inggris: 'who' },
    { indonesia: 'sini', inggris: 'here' },
    { indonesia: 'sore', inggris: 'late afternoon / evening' },
    { indonesia: 'suami', inggris: 'husband' },
    { indonesia: 'suara', inggris: 'voice / sound' },
    { indonesia: 'sudah', inggris: 'already' },
    { indonesia: 'suka', inggris: 'like' },
    { indonesia: 'sungai', inggris: 'river' },
    { indonesia: 'surat', inggris: 'letter' },
    { indonesia: 'susah', inggris: 'difficult' },
    { indonesia: 'susu', inggris: 'milk' },
    { indonesia: 'tahu', inggris: 'know / tofu' },
    { indonesia: 'tahun', inggris: 'year' },
    { indonesia: 'takut', inggris: 'afraid' },
    { indonesia: 'taman', inggris: 'park / garden' },
    { indonesia: 'tanah', inggris: 'soil / land' },
    { indonesia: 'tangan', inggris: 'hand' },
    { indonesia: 'tanggal', inggris: 'date' },
    { indonesia: 'tanya', inggris: 'ask' },
    { indonesia: 'tapi', inggris: 'but' },
    { indonesia: 'tas', inggris: 'bag' },
    { indonesia: 'teh', inggris: 'tea' },
    { indonesia: 'teman', inggris: 'friend' },
    { indonesia: 'tempat', inggris: 'place' },
    { indonesia: 'tengah', inggris: 'middle / center' },
    { indonesia: 'tentang', inggris: 'about' },
    { indonesia: 'terakhir', inggris: 'last' },
    { indonesia: 'terbang', inggris: 'fly' },
    { indonesia: 'terima kasih', inggris: 'thank you' },
    { indonesia: 'tertawa', inggris: 'laugh' },
    { indonesia: 'tetapi', inggris: 'but / however' },
    { indonesia: 'tidur', inggris: 'sleep' },
    { indonesia: 'timur', inggris: 'east' },
    { indonesia: 'tinggi', inggris: 'tall / high' },
    { indonesia: 'toko', inggris: 'shop / store' },
    { indonesia: 'topi', inggris: 'hat' },
    { indonesia: 'tua', inggris: 'old' },
    { indonesia: 'tulang', inggris: 'bone' },
    { indonesia: 'tulis', inggris: 'write' },
    { indonesia: 'tunggu', inggris: 'wait' },
    { indonesia: 'uang', inggris: 'money' },
    { indonesia: 'udara', inggris: 'air' },
    { indonesia: 'utara', inggris: 'north' },
    { indonesia: 'wajah', inggris: 'face' },
    { indonesia: 'waktu', inggris: 'time' },
    { indonesia: 'wanita', inggris: 'woman' },
    { indonesia: 'warna', inggris: 'color' },
    { indonesia: 'ya', inggris: 'yes' },
    { indonesia: 'yang', inggris: 'which / that' }
];